### ISSUE TITLE
Document huawei cloud support

### ISSUE THREAD

**Issue by xd009642** [Qovery/engine#168]
In my experience Huawei cloud is pretty similar to S3 (though occasionally some things are just ever so slightly different). It would be nice if huawei cloud could be tested and added to the readme if it works. Just because it's probably the most popular cloud provider in china

**Comment by deimosfr** [comment]
Hi, at the moment, we did not plan to manage the Huawei cloud. You're the very first one asking for it.

What I suggest is to add your wishes to the roadmap https://roadmap.qovery.com. The more users will vote for it, the more the chance to integrate it will occur :)

Thanks

**Comment by xd009642** [comment]
Done, I also mentioned alibaba cloud as they're the two dominant cloud providers in china. I'll close this as there's now a roadmap entry
