### ISSUE TITLE
Feature request - qovery deploy button

### ISSUE THREAD

**Issue by audiBookning** [Qovery/engine#255]
It seems that Qovery is heavily inspired by heroku among other things.

I was wondering if Qovery already has a feature similar to [heroku-button](https://devcenter.heroku.com/articles/heroku-button)?
And if not, that it would be considered as a new feature.

**Comment by acarranoqovery** [comment]
Hi @audiBookning ,

thanks for your feedback but we won't implement this feature

have a nice day!
