### ISSUE TITLE
Postgres Connection URL not compatible with Python database drivers. 

### ISSUE THREAD

**Issue by harshitsinghai77** [Qovery/engine#457]
I wanted to create a database in Qovery. I grabbed the `db_url` from the UI.

`DB_URL = "postgresql://postgres:_Ij=de-6S8B$avgXtFN?@U-+0gnAZ0x!@z3baa5944-postgresql.qovery.io:5432/postgres"`
(Don't worry, this database does not exist in Qovery anymore.)

I'm getting an error. 
```
File "/home/harshitsinghai/.pyenv/versions/3.9.5/lib/python3.9/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '_Ij=de-6S8B$avgXtFN'
```

I deleted the database, created a new one, and tried again with the new db_url. But I'm getting the same error.

I don't think using `postgres` as the default DB username is a good idea. It will be confused by many URL parsers. 

`postgresql://postgres:U8T%2T#YjO#-ep-MjGBcJ_` this string might be creating confusion for lots of parsers.

Either give the user the option to change the default username or use something more generic.

Code Snippet
```python
QOVERY_URL = "postgresql://postgres:U8T%2T#YjO#-ep-MjGBcJ_@!fgczi!%g@z794a99a3-postgresql.qovery.io:5432/postgres"
database = databases.Database(QOVERY_URL)
metadata = sqlalchemy.MetaData()

engine = sqlalchemy.create_engine(QOVERY_URL)
```

**Comment by evoxmusic** [comment]
Hi, please use the [community forum](https://discuss.qovery.com) to get some help on how to use Qovery.
