### ISSUE TITLE
Hey this is verry bad behaviour from you guys

### ISSUE THREAD

**Issue by why-serious-bro** [Qovery/engine#501]
https://discuss.qovery.com/t/hey-i-got-banned-from-discord-for-asking-help/819?u=why-serious-bro

I didn't even did anything bad or said anything you guys can check recent logs of my messages. I was just asking to approve my forum request as its been 4 days then some moderator banned me without any proofs my quovery account is banned. I didnt even received single mail saying my account got banned because I didn't do anything. I hope you take this matter verry seriously and make that moderator not to do whatever he wants

**Comment by why-serious-bro** [comment]
https://discuss.qovery.com/t/why-do-we-need-to-wait-for-weeks-to-use-quovery-even-if-we-have-an-account/821?u=why-serious-bro

**Comment by evoxmusic** [comment]
Hi, I close the issue - please do send an email to support [at] {company} dot com

**Comment by why-serious-bro** [comment]
> Hi, I close the issue - please do send an email to support [at] {company} dot com

Bruh i got banned from your discussion forum to saying spamming here and discord lool

Is this how a company should respond?? Without rectifying my issue why do you want to act like dictator and ban ?
