### ISSUE TITLE
Why does the readme say you support certain cloud providers even though you don't?

### ISSUE THREAD

**Issue by pitoriex** [Qovery/engine#517]
The readme says that you support AWS, Digital Ocean, Azure, GCP and Scaleway. But as I can see it only AWS and Digital Ocean are supported currently? Why are the others also listed under that heading?
Same with Build Platforms, Container registries and Monitoring services.
This is really confusing when you try to understand if this piece of software is something I'd be interested in using.

**Comment by Leafgard** [comment]
Hey @pitoriex,
I believe what you search is under [Advanced Guides](https://hub.qovery.com/guides/advanced/) on Qovery Hub.

Hope this helps.

**Comment by OmgImAlexis** [comment]
Also the ones that are listed for the future don't even have working vote links. They go to the docs site which then has another link to vote which then takes you to a 404.

**Comment by Leafgard** [comment]
@OmgImAlexis True. You can find the working roadmap link [here](https://roadmap.qovery.com/roadmap).

**Comment by evoxmusic** [comment]
Thanks Yann 🙏 sorry about the dead links, we recently changed our roadmap tool. @Albanetonnellier can you fix the dead links from our documentation? Thank you 🙏

**Comment by OmgImAlexis** [comment]
> Deploy your apps on any Cloud providers in just a few seconds zap

Would be nice to see a superscript 1 added to the "any Cloud providers" with a link to the roadmap or the section further down the readme that explains which ones are supported and which ones are coming in the future.
