### ISSUE TITLE
Migrate away from deprecated `heroku/builder-classic:22` CNB builder image

### ISSUE THREAD

**Issue by edmorley** [Qovery/engine#741]
Hi 👋 

This project uses Heroku's `heroku/builder-classic:22` CNB builder image:
https://github.com/Qovery/engine/blob/056c1951cdb78d065260b927b7992bd0aac18762/src/build_platform/local_docker.rs#L30-L31

We have deprecated this builder image as of https://github.com/heroku/cnb-builder-images/pull/429.

Please migrate to `heroku/builder:22` or `heroku/builder:20`, to continue to receive security updates, and to avoid disruption when the build time deprecation warning is upgraded to an error in the future.

More information on the difference between the various builder images can be seen here:
https://github.com/heroku/cnb-builder-images#heroku-cnb-builder-images

The repo URL for the builder images has also changed, see #739.

**Comment by edmorley** [comment]
Gentle nudge that builds using these images will start erroring in the future, plus the underlying images themselves will stop receiving security updates.

**Comment by edmorley** [comment]
@erebe @benjaminch ^

**Comment by edmorley** [comment]
> Gentle nudge that builds using these images will start erroring in the future, plus the underlying images themselves will stop receiving security updates.

This will be happening within the next couple of weeks in https://github.com/heroku/cnb-builder-images. We'll be adding an env var override for the errors, but I strongly recommend you switch from `heroku/builder-classic:22` to `heroku/builder:*` as soon as possible.

**Comment by benjaminch** [comment]
Hey @edmorley, it should be done => https://github.com/search?q=repo%3AQovery%2Fengine%20heroku%2Fbuilder%3A&type=code

**Comment by edmorley** [comment]
@benjaminch Ah thank you, I see it happened in:
https://github.com/Qovery/engine/commit/9323ce12b4af7936d445b05ef4096511496ec4b2#diff-1d6d87da9c944d92a413b97b36c22686cf328b99b62adacd3a86e2022b4df409R32

Since there was no PR callback reference visible in the history of this issue I hadn't seen the change.
