### ISSUE TITLE
`kube` dependency v0.86.0 is yanked

### ISSUE THREAD

**Issue by ismaelgonval** [Qovery/engine#742]
First, congrats for this awesome project. I'm triying to create a pilot project with this tool but I've found that `kube` dependency seems broken.

Currently, this project depends on `kube` version `0.86.0` but it seems [yanked in crate.io](https://crates.io/crates/kube/0.86.0).

If I tried to build it locally or use it as lib, it seems that it is not possible to compile the project:

```cargo build``` output:
> error: failed to select a version for the requirement `kube = "^0.86.0"`
candidate versions found which didn't match: 0.88.1, 0.88.0, 0.87.2, ...
location searched: crates.io index
required by package `qovery-engine v0.1.0 (/home/xxx/qovery/engine)`
perhaps a crate was updated and forgotten to be re-vendored?

_EDIT: it seems that `0.87.x` works fine._

**Comment by benjaminch** [comment]
Hey @ismaelgonval !

Thanks :)

Indeed it has been fixed, let me know if it looks better :)

https://github.com/Qovery/engine/blob/main/Cargo.toml#L47

Cheers
