### ISSUE TITLE
Update default CNB builder image to `heroku/builder:24`

### ISSUE THREAD

**Issue by edmorley** [Qovery/engine#743]
We (Heroku) released `heroku/builder:24`, our new CNB builder image version based upon Ubuntu 24.04 LTS, in June:
https://github.com/heroku/buildpacks/discussions/12
https://github.com/heroku/cnb-builder-images#available-images

Currently this project's default CNB builder image is `heroku/builder:22`:
https://github.com/Qovery/engine/blob/f11361bd076fa07ded51ec1ff535ba6946ed3451/src/build_platform/local_docker.rs#L31-L32

It would be great to update the default CNB builder image to `heroku/builder:24`.

The `heroku/builder:24` builder is now a multi-architecture image (AMD64 + ARM64), and offers smaller run image sizes thanks to dropping unnecessary build-time dependencies from the run image. The list of included buildpacks (and their versions) is identical between `heroku/builder:22` and `heroku/builder:24`. 

For more information on the differences between the two images, see:
https://devcenter.heroku.com/articles/heroku-24-stack#what-s-new
https://devcenter.heroku.com/articles/heroku-24-stack#upgrade-notes
https://devcenter.heroku.com/articles/stack-packages

**Comment by benjaminch** [comment]
Hello @edmorley 

Thanks for reaching !
I will have a look and let you know once released.

Cheers

**Comment by benjaminch** [comment]
Hey @edmorley,

Default builder has been updated to 24. (CF https://github.com/Qovery/engine/blob/main/src/build_platform/local_docker.rs#L37)

I am closing this one for the time being, please do not hesitate to re-open if you see any issue.

Cheers

**Comment by edmorley** [comment]
@benjaminch Great! Thank you for the update :-)
